"use client";

import React, { useState, useRef, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import {
  Radar,
  LayoutDashboard,
  MapIcon,
  Megaphone,
  Bell,
  Settings,
  HelpCircle,
  MessageSquarePlus,
  PanelLeftClose,
  PanelLeftOpen,
  Send,
  Paperclip,
  Mic,
  Sparkles,
  Waves,
  Car,
  Flame,
  MapPin,
  ChevronRight,
  X,
  ShieldAlert,
  Clock,
  BadgeCheck,
} from "lucide-react";

/* ----------------------------------------------------------------------- */
/*  Mock / demonstration data                                              */
/* ----------------------------------------------------------------------- */

const RECENT_CONVERSATIONS = [
  { id: "c1", title: "Flood safety near Nabin Nagar" },
  { id: "c2", title: "How to report a road accident" },
  { id: "c3", title: "Fire evacuation checklist" },
];

const SUGGESTIONS = [
  {
    id: "flood",
    emoji: "🌊",
    icon: Waves,
    color: "#38bdf8",
    title: "Flood Safety",
    prompt: "What should I do during a flood?",
  },
  {
    id: "accident",
    emoji: "🚗",
    icon: Car,
    color: "#f43f5e",
    title: "Road Accident",
    prompt: "What information should I provide when reporting an accident?",
  },
  {
    id: "fire",
    emoji: "🔥",
    icon: Flame,
    color: "#fb923c",
    title: "Fire Emergency",
    prompt: "What are the immediate safety steps during a fire?",
  },
  {
    id: "nearby",
    emoji: "📍",
    icon: MapPin,
    color: "#a78bfa",
    title: "Nearby Incidents",
    prompt: "Show me reported emergencies near my location.",
  },
];

const QUICK_ACTIONS = [
  { id: "report", label: "Report an Emergency", icon: Megaphone },
  { id: "map", label: "View Live Map", icon: MapIcon },
  { id: "nearby", label: "Find Nearby Incidents", icon: MapPin },
  { id: "safety", label: "Get Safety Guidance", icon: ShieldAlert },
];

const NEARBY_INCIDENTS = [
  { id: "i1", type: "Flood", severity: "Critical", location: "Nabin Nagar Road", status: "Verified", time: "6 min ago" },
  { id: "i2", type: "Fire", severity: "High", location: "Fancy Bazaar Market", status: "Community Reported", time: "18 min ago" },
  { id: "i3", type: "Accident", severity: "Moderate", location: "GS Road Flyover", status: "Verified", time: "41 min ago" },
];

const SEVERITY_COLOR = {
  Critical: "#f43f5e",
  High: "#fb923c",
  Moderate: "#facc15",
  Resolved: "#34d399",
};

const CATEGORY_ICON = { Flood: Waves, Fire: Flame, Accident: Car, Roadblock: MapPin };

const MOCK_REPLY_TEXT =
  "This is a demonstration response only — not verified official emergency guidance and not generated by a live AI model. In the completed platform, this panel will connect to a real backend for accurate, cited safety information.";

/* ----------------------------------------------------------------------- */
/*  Small building blocks                                                  */
/* ----------------------------------------------------------------------- */

function GlowOrb({ size = 40 }) {
  return (
    <div className="relative shrink-0" style={{ width: size, height: size }}>
      <div
        className="absolute inset-0 rounded-full animate-pulse"
        style={{
          background: "radial-gradient(circle at 30% 30%, #67e8f9, #0891b2 60%, transparent 80%)",
          filter: "blur(1px)",
        }}
      />
      <div className="absolute inset-0 grid place-items-center">
        <Sparkles className="h-1/2 w-1/2 text-white" />
      </div>
    </div>
  );
}

function TypingIndicator() {
  return (
    <div className="flex items-center gap-1.5 rounded-2xl bg-slate-800/70 px-4 py-3">
      {[0, 1, 2].map((i) => (
        <motion.span
          key={i}
          className="h-1.5 w-1.5 rounded-full bg-cyan-400"
          animate={{ opacity: [0.3, 1, 0.3], y: [0, -3, 0] }}
          transition={{ duration: 1, repeat: Infinity, delay: i * 0.15 }}
        />
      ))}
    </div>
  );
}

function StatusBadge({ status }) {
  const verified = status === "Verified";
  return (
    <span
      className={`inline-flex items-center gap-1 rounded-full px-2 py-0.5 text-[10px] font-medium ring-1 ${
        verified
          ? "bg-sky-500/10 text-sky-300 ring-sky-500/30"
          : "bg-slate-500/10 text-slate-400 ring-slate-500/30"
      }`}
    >
      {verified && <BadgeCheck className="h-3 w-3" />}
      {status}
    </span>
  );
}

function EmergencyInfoCard({ incident }) {
  const Icon = CATEGORY_ICON[incident.type] || MapPin;
  const color = SEVERITY_COLOR[incident.severity];
  return (
    <div className="rounded-xl border border-slate-800 bg-slate-900/70 p-3.5">
      <div className="flex items-start justify-between gap-2">
        <div className="flex items-center gap-2">
          <span className="grid h-8 w-8 place-items-center rounded-lg" style={{ backgroundColor: `${color}1f`, color }}>
            <Icon className="h-4 w-4" />
          </span>
          <div>
            <p className="text-xs font-medium text-slate-200">{incident.type} incident</p>
            <p className="text-[11px] text-slate-500">{incident.location}</p>
          </div>
        </div>
        <span className="flex items-center gap-1 text-[11px] font-medium" style={{ color }}>
          {incident.severity}
        </span>
      </div>
      <div className="mt-2.5 flex items-center justify-between">
        <div className="flex items-center gap-2">
          <StatusBadge status={incident.status} />
          <span className="flex items-center gap-1 text-[11px] text-slate-500">
            <Clock className="h-3 w-3" /> {incident.time}
          </span>
        </div>
      </div>
      <div className="mt-3 flex gap-2">
        <button className="flex-1 rounded-lg bg-cyan-500/10 py-1.5 text-[11px] font-medium text-cyan-300 ring-1 ring-cyan-500/30 hover:bg-cyan-500/20">
          View on Map
        </button>
        <button className="flex-1 rounded-lg bg-slate-800 py-1.5 text-[11px] font-medium text-slate-300 hover:bg-slate-700">
          Report Incident
        </button>
      </div>
    </div>
  );
}

/* ----------------------------------------------------------------------- */
/*  Sidebar                                                                 */
/* ----------------------------------------------------------------------- */

function AssistantSidebar({ collapsed, onToggle, onNewChat }) {
  const navItems = [
    { label: "Dashboard", icon: LayoutDashboard },
    { label: "Live Emergency Map", icon: MapIcon },
    { label: "Report an Emergency", icon: Megaphone },
    { label: "Nearby Alerts", icon: Bell },
  ];

  return (
    <motion.aside
      animate={{ width: collapsed ? 0 : 264 }}
      transition={{ duration: 0.2 }}
      className="hidden shrink-0 overflow-hidden border-r border-slate-800/80 bg-slate-950/80 backdrop-blur-xl md:flex md:flex-col"
    >
      <div className="flex w-64 flex-1 flex-col">
        <div className="flex items-center gap-2.5 px-5 py-5">
          <div className="grid h-8 w-8 place-items-center rounded-xl bg-gradient-to-br from-cyan-400 to-sky-600">
            <Radar className="h-4.5 w-4.5 text-slate-950" />
          </div>
          <span className="text-base font-semibold tracking-tight text-white">SmartCity</span>
        </div>

        <div className="px-3">
          <button
            onClick={onNewChat}
            className="flex w-full items-center gap-2 rounded-xl border border-cyan-500/30 bg-cyan-500/10 px-3 py-2.5 text-sm font-medium text-cyan-300 hover:bg-cyan-500/20"
          >
            <MessageSquarePlus className="h-4 w-4" /> New Chat
          </button>
        </div>

        <div className="mt-5 flex-1 overflow-y-auto px-3">
          <p className="px-2 text-[11px] font-medium uppercase tracking-wide text-slate-600">Recent</p>
          <div className="mt-1.5 space-y-0.5">
            {RECENT_CONVERSATIONS.map((c) => (
              <button
                key={c.id}
                className="block w-full truncate rounded-lg px-2.5 py-2 text-left text-xs text-slate-400 hover:bg-slate-800/60 hover:text-slate-200"
              >
                {c.title}
              </button>
            ))}
          </div>

          <p className="mt-5 px-2 text-[11px] font-medium uppercase tracking-wide text-slate-600">Navigate</p>
          <div className="mt-1.5 space-y-0.5">
            {navItems.map((item) => {
              const Icon = item.icon;
              return (
                <button
                  key={item.label}
                  className="flex w-full items-center gap-2.5 rounded-lg px-2.5 py-2 text-left text-xs text-slate-400 hover:bg-slate-800/60 hover:text-slate-200"
                >
                  <Icon className="h-3.5 w-3.5 text-slate-500" /> {item.label}
                </button>
              );
            })}
          </div>
        </div>

        <div className="space-y-0.5 border-t border-slate-800/80 px-3 py-3">
          <button className="flex w-full items-center gap-2.5 rounded-lg px-2.5 py-2 text-left text-xs text-slate-400 hover:bg-slate-800/60 hover:text-slate-200">
            <Settings className="h-3.5 w-3.5" /> Settings
          </button>
          <button className="flex w-full items-center gap-2.5 rounded-lg px-2.5 py-2 text-left text-xs text-slate-400 hover:bg-slate-800/60 hover:text-slate-200">
            <HelpCircle className="h-3.5 w-3.5" /> Help
          </button>
        </div>

        <div className="m-3 flex items-center gap-2.5 rounded-xl border border-slate-800/80 bg-slate-900/70 p-2.5">
          <span className="grid h-8 w-8 place-items-center rounded-full bg-gradient-to-br from-cyan-400 to-violet-500 text-xs font-semibold text-slate-950">
            PD
          </span>
          <div className="min-w-0">
            <p className="truncate text-xs font-medium text-slate-200">Priyam Deka</p>
            <p className="truncate text-[11px] text-slate-500">Verified Citizen</p>
          </div>
        </div>
      </div>
    </motion.aside>
  );
}

/* ----------------------------------------------------------------------- */
/*  Chat header                                                             */
/* ----------------------------------------------------------------------- */

function ChatHeader({ collapsed, onToggle, rightOpen, onToggleRight }) {
  return (
    <div className="flex items-center justify-between border-b border-slate-800/80 px-4 py-3.5 sm:px-6">
      <div className="flex items-center gap-3">
        <button
          onClick={onToggle}
          className="grid h-8 w-8 place-items-center rounded-lg border border-slate-800 text-slate-400 hover:text-white"
        >
          {collapsed ? <PanelLeftOpen className="h-4 w-4" /> : <PanelLeftClose className="h-4 w-4" />}
        </button>
        <div>
          <p className="text-sm font-semibold text-white">AI Emergency Assistant</p>
          <p className="text-[11px] text-slate-500">Demonstration only — not live AI or verified data</p>
        </div>
      </div>
      <button
        onClick={onToggleRight}
        className="rounded-lg border border-slate-800 px-3 py-1.5 text-xs text-slate-400 hover:text-white"
      >
        {rightOpen ? "Hide info panel" : "Show info panel"}
      </button>
    </div>
  );
}

/* ----------------------------------------------------------------------- */
/*  Welcome screen                                                          */
/* ----------------------------------------------------------------------- */

function WelcomeScreen({ onPick }) {
  return (
    <div className="mx-auto flex h-full max-w-2xl flex-col items-center justify-center px-4 text-center">
      <GlowOrb size={56} />
      <h1 className="mt-5 text-2xl font-semibold text-white">Your AI Emergency Assistant</h1>
      <p className="mt-2 max-w-md text-sm text-slate-400">
        I'm here to help you understand emergency situations, find relevant safety information, and navigate the
        SmartCity platform.
      </p>

      <div className="mt-8 grid w-full grid-cols-1 gap-3 sm:grid-cols-2">
        {SUGGESTIONS.map((s) => {
          const Icon = s.icon;
          return (
            <button
              key={s.id}
              onClick={() => onPick(s.prompt)}
              className="group flex items-start gap-3 rounded-2xl border border-slate-800 bg-slate-900/60 p-4 text-left transition-colors hover:border-slate-700"
            >
              <span
                className="grid h-9 w-9 shrink-0 place-items-center rounded-xl transition-transform group-hover:scale-110"
                style={{ backgroundColor: `${s.color}1f`, color: s.color }}
              >
                <Icon className="h-4.5 w-4.5" />
              </span>
              <span>
                <span className="block text-sm font-medium text-slate-200">
                  {s.emoji} {s.title}
                </span>
                <span className="mt-0.5 block text-xs text-slate-500">{s.prompt}</span>
              </span>
            </button>
          );
        })}
      </div>
    </div>
  );
}

/* ----------------------------------------------------------------------- */
/*  Chat message                                                            */
/* ----------------------------------------------------------------------- */

function ChatMessage({ role, text, time, incident }) {
  const isUser = role === "user";
  return (
    <motion.div
      initial={{ opacity: 0, y: 8 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.25 }}
      className={`flex items-start gap-2.5 ${isUser ? "flex-row-reverse" : ""}`}
    >
      {isUser ? (
        <span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-gradient-to-br from-cyan-400 to-violet-500 text-[10px] font-semibold text-slate-950">
          PD
        </span>
      ) : (
        <span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-slate-800">
          <Sparkles className="h-3.5 w-3.5 text-cyan-400" />
        </span>
      )}
      <div className={`max-w-[80%] ${isUser ? "items-end" : "items-start"} flex flex-col gap-1.5`}>
        <div
          className={`rounded-2xl px-4 py-2.5 text-sm leading-relaxed ${
            isUser
              ? "bg-cyan-500/15 text-cyan-100 ring-1 ring-cyan-500/30"
              : "bg-slate-800/70 text-slate-200"
          }`}
        >
          {text}
        </div>
        {incident && <EmergencyInfoCard incident={incident} />}
        <span className="px-1 text-[10px] text-slate-600">{time}</span>
      </div>
    </motion.div>
  );
}

/* ----------------------------------------------------------------------- */
/*  Quick actions                                                           */
/* ----------------------------------------------------------------------- */

function QuickActions({ onAction }) {
  return (
    <div className="flex flex-wrap gap-1.5 px-4 pb-2 sm:px-6">
      {QUICK_ACTIONS.map((a) => {
        const Icon = a.icon;
        return (
          <button
            key={a.id}
            onClick={() => onAction(a)}
            className="flex items-center gap-1.5 rounded-full border border-slate-800 bg-slate-900/60 px-3 py-1.5 text-[11px] text-slate-400 transition-colors hover:border-cyan-500/40 hover:text-cyan-300"
          >
            <Icon className="h-3.5 w-3.5" /> {a.label}
          </button>
        );
      })}
    </div>
  );
}

/* ----------------------------------------------------------------------- */
/*  Message input                                                           */
/* ----------------------------------------------------------------------- */

function MessageInput({ value, onChange, onSend, disabled }) {
  const textareaRef = useRef(null);

  useEffect(() => {
    const el = textareaRef.current;
    if (!el) return;
    el.style.height = "auto";
    el.style.height = Math.min(el.scrollHeight, 160) + "px";
  }, [value]);

  function handleKeyDown(e) {
    if (e.key === "Enter" && !e.shiftKey) {
      e.preventDefault();
      onSend();
    }
  }

  return (
    <div className="border-t border-slate-800/80 px-4 py-3 sm:px-6">
      <div className="flex items-end gap-2 rounded-2xl border border-slate-800 bg-slate-900/70 px-3 py-2 focus-within:border-cyan-500/50">
        <button type="button" className="grid h-8 w-8 shrink-0 place-items-center rounded-lg text-slate-500 hover:text-slate-300">
          <Paperclip className="h-4 w-4" />
        </button>
        <textarea
          ref={textareaRef}
          rows={1}
          value={value}
          onChange={(e) => onChange(e.target.value)}
          onKeyDown={handleKeyDown}
          placeholder="Describe your emergency or ask me anything..."
          className="max-h-40 flex-1 resize-none bg-transparent py-1.5 text-sm text-slate-200 placeholder:text-slate-600 focus:outline-none"
        />
        <button type="button" className="grid h-8 w-8 shrink-0 place-items-center rounded-lg text-slate-500 hover:text-slate-300">
          <Mic className="h-4 w-4" />
        </button>
        <button
          type="button"
          onClick={onSend}
          disabled={disabled}
          className="grid h-8 w-8 shrink-0 place-items-center rounded-lg bg-cyan-500 text-slate-950 transition-opacity hover:bg-cyan-400 disabled:cursor-not-allowed disabled:opacity-30"
        >
          <Send className="h-4 w-4" />
        </button>
      </div>
      <p className="mt-1.5 text-center text-[10px] text-slate-600">
        Enter to send · Shift + Enter for a new line
      </p>
    </div>
  );
}

/* ----------------------------------------------------------------------- */
/*  Right info panel                                                        */
/* ----------------------------------------------------------------------- */

function InfoPanel({ open, onClose }) {
  return (
    <AnimatePresence>
      {open && (
        <motion.aside
          initial={{ width: 0, opacity: 0 }}
          animate={{ width: 300, opacity: 1 }}
          exit={{ width: 0, opacity: 0 }}
          transition={{ duration: 0.2 }}
          className="hidden shrink-0 overflow-hidden border-l border-slate-800/80 bg-slate-950/80 backdrop-blur-xl lg:flex lg:flex-col"
        >
          <div className="flex w-[300px] flex-1 flex-col">
            <div className="flex items-center justify-between border-b border-slate-800/80 px-4 py-4">
              <p className="text-sm font-semibold text-white">Nearby Incidents</p>
              <button onClick={onClose} className="text-slate-500 hover:text-slate-200">
                <X className="h-4 w-4" />
              </button>
            </div>
            <div className="flex-1 space-y-3 overflow-y-auto px-4 py-4">
              {NEARBY_INCIDENTS.map((inc) => (
                <EmergencyInfoCard key={inc.id} incident={inc} />
              ))}
            </div>
            <div className="space-y-2 border-t border-slate-800/80 px-4 py-4">
              <button className="flex w-full items-center justify-between rounded-lg bg-rose-500/10 px-3 py-2 text-xs font-medium text-rose-300 ring-1 ring-rose-500/30 hover:bg-rose-500/20">
                Report an Emergency <ChevronRight className="h-3.5 w-3.5" />
              </button>
              <p className="px-1 text-[10px] text-slate-600">
                Emergency contacts and safety resources will appear here once connected to live data.
              </p>
            </div>
          </div>
        </motion.aside>
      )}
    </AnimatePresence>
  );
}

/* ----------------------------------------------------------------------- */
/*  Main component                                                          */
/* ----------------------------------------------------------------------- */

export default function AIEmergencyAssistant() {
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false);
  const [rightOpen, setRightOpen] = useState(true);
  const [messages, setMessages] = useState([]);
  const [input, setInput] = useState("");
  const [typing, setTyping] = useState(false);
  const scrollRef = useRef(null);

  useEffect(() => {
    scrollRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, typing]);

  function sendMessage(text) {
    const trimmed = (text ?? input).trim();
    if (!trimmed) return;

    const userMsg = { id: crypto.randomUUID(), role: "user", text: trimmed, time: "Just now" };
    setMessages((m) => [...m, userMsg]);
    setInput("");
    setTyping(true);

    setTimeout(() => {
      setTyping(false);
      const attachIncident = /nearby|incident|flood|fire|accident/i.test(trimmed)
        ? NEARBY_INCIDENTS[0]
        : null;
      setMessages((m) => [
        ...m,
        {
          id: crypto.randomUUID(),
          role: "assistant",
          text: MOCK_REPLY_TEXT,
          time: "Just now",
          incident: attachIncident,
        },
      ]);
    }, 1100);
  }

  function handleQuickAction(action) {
    if (action.id === "safety") {
      sendMessage("What safety precautions should I take?");
    } else {
      sendMessage(`(Demo) Navigating to: ${action.label}`);
    }
  }

  function handleNewChat() {
    setMessages([]);
    setInput("");
  }

  return (
    <div className="flex h-screen w-full bg-slate-950 text-slate-200" style={{ fontFamily: "Inter, ui-sans-serif, system-ui" }}>
      <AssistantSidebar
        collapsed={sidebarCollapsed}
        onToggle={() => setSidebarCollapsed((v) => !v)}
        onNewChat={handleNewChat}
      />

      <div className="flex min-w-0 flex-1 flex-col">
        <ChatHeader
          collapsed={sidebarCollapsed}
          onToggle={() => setSidebarCollapsed((v) => !v)}
          rightOpen={rightOpen}
          onToggleRight={() => setRightOpen((v) => !v)}
        />

        <div className="flex-1 overflow-y-auto">
          {messages.length === 0 ? (
            <WelcomeScreen onPick={(p) => sendMessage(p)} />
          ) : (
            <div className="mx-auto flex max-w-2xl flex-col gap-5 px-4 py-6 sm:px-6">
              {messages.map((m) => (
                <ChatMessage key={m.id} role={m.role} text={m.text} time={m.time} incident={m.incident} />
              ))}
              {typing && (
                <div className="flex items-start gap-2.5">
                  <span className="grid h-7 w-7 shrink-0 place-items-center rounded-full bg-slate-800">
                    <Sparkles className="h-3.5 w-3.5 text-cyan-400" />
                  </span>
                  <TypingIndicator />
                </div>
              )}
              <div ref={scrollRef} />
            </div>
          )}
        </div>

        <QuickActions onAction={handleQuickAction} />
        <MessageInput value={input} onChange={setInput} onSend={() => sendMessage()} disabled={!input.trim()} />
      </div>

      <InfoPanel open={rightOpen} onClose={() => setRightOpen(false)} />
    </div>
  );
}
